In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import os

customers = pd.read_csv("/Users/aksharadarapaneni/data-analyst-portfolio/project-1-ecommerce/data/olist_customers_dataset.csv")
order_items = pd.read_csv("/Users/aksharadarapaneni/data-analyst-portfolio/project-1-ecommerce/data/olist_order_items_dataset.csv")
order_payments = pd.read_csv("/Users/aksharadarapaneni/data-analyst-portfolio/project-1-ecommerce/data/olist_order_payments_dataset.csv")
order_reviews= pd.read_csv("/Users/aksharadarapaneni/data-analyst-portfolio/project-1-ecommerce/data/olist_order_reviews_dataset.csv")
orders = pd.read_csv("/Users/aksharadarapaneni/data-analyst-portfolio/project-1-ecommerce/data/olist_orders_dataset.csv")
products = pd.read_csv("/Users/aksharadarapaneni/data-analyst-portfolio/project-1-ecommerce/data/olist_products_dataset.csv")
sellers= pd.read_csv("/Users/aksharadarapaneni/data-analyst-portfolio/project-1-ecommerce/data/olist_sellers_dataset.csv")
category_translation = pd.read_csv("/Users/aksharadarapaneni/data-analyst-portfolio/project-1-ecommerce/data/product_category_name_translation.csv")

print("all datasets loaded successfully")

all datasets loaded successfully

In [2]:
print("customers:" , customers.shape)
print("order_items:",order_items.shape)
print("order_payments:",order_payments.shape)
print("order_reviews:",order_reviews.shape)
print("orders:",orders.shape)
print("products:",products.shape)
print("sellers:",sellers.shape)
print("category_translation:",category_translation.shape)

customers: (99441, 5)
order_items: (112650, 7)
order_payments: (103886, 5)
order_reviews: (99224, 7)
orders: (99441, 8)
products: (32951, 9)
sellers: (3095, 4)
category_translation: (71, 2)

In [3]:
orders.groupby("order_status").order_id.count()

order_status
approved           2
canceled         625
created            5
delivered      96478
invoiced         314
processing       301
shipped         1107
unavailable      609
Name: order_id, dtype: int64

In [4]:
print("orders:",orders.isnull().sum())
print("order_items:",order_items.isnull().sum())
print("customers:",customers.isnull().sum())
print("order_payments:",order_payments.isnull().sum())
print("products:",products.isnull().sum())
print("sellers:",sellers.isnull().sum())
print("order_reviews:",order_reviews.isnull().sum())
print("category_translation:",category_translation.isnull().sum())

orders: order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64
order_items: order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64
customers: customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64
order_payments: order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64
products: product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64
sellers: seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64
order_reviews: review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64
category_translation: product_category_name            0
product_category_name_english    0
dtype: int64

In [5]:
products.dropna(subset=['product_category_name'],inplace=True)

In [6]:
products.shape

(32341, 9)

In [7]:
print("products:",products.isnull().sum())

products: product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              1
product_length_cm             1
product_height_cm             1
product_width_cm              1
dtype: int64

In [8]:
orders.dtypes

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [9]:
orders['order_purchase_timestamp']=pd.to_datetime(orders['order_purchase_timestamp'])

In [10]:
orders.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                        object
order_delivered_carrier_date             object
order_delivered_customer_date            object
order_estimated_delivery_date            object
dtype: object

In [11]:
orders['order_delivered_carrier_date']=pd.to_datetime(orders['order_purchase_timestamp'])
orders['order_delivered_customer_date']=pd.to_datetime(orders['order_delivered_customer_date'])
orders['order_estimated_delivery_date']=pd.to_datetime(orders['order_estimated_delivery_date'])

In [12]:
orders.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                        object
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [13]:
products=products.merge(category_translation,on='product_category_name')
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery
1,6a2fb4dd53d2cdb88e0432f1284a004c,perfumaria,39.0,346.0,2.0,400.0,27.0,5.0,20.0,perfumery
2,0d009643171aee696f4733340bc2fdd0,perfumaria,52.0,150.0,1.0,422.0,21.0,16.0,18.0,perfumery
3,b1eae565a61935e0011ee7682fef9dc9,perfumaria,49.0,460.0,2.0,267.0,17.0,13.0,17.0,perfumery
4,8da90b37f0fb171b4877c124f965b1f6,perfumaria,56.0,733.0,3.0,377.0,18.0,13.0,15.0,perfumery

In [14]:
products.shape

(32328, 10)

In [15]:
orders['order_approved_at']=pd.to_datetime(orders['order_approved_at'])

In [16]:
category_translation.columns

Index(['product_category_name', 'product_category_name_english'], dtype='object')

In [21]:
orders_delivered= orders[orders['order_status']=='delivered']
orders_delivered.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-02 10:56:33,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-24 20:41:37,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 08:38:49,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-18 19:28:06,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-13 21:18:39,2018-02-16 18:17:02,2018-02-26